name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Publish Chrome Web Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - run: yarn --immutable
      - run: yarn biome ci
      - run: yarn lint:tsc

      - name: Get version number
        id: semver
        run: ./scripts/semver.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn prod
        if: steps.semver.outputs.VERSION != ''
        env:
          PACKAGE_VERSION: ${{ steps.semver.outputs.VERSION }}
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v4.0.0
        if: steps.semver.outputs.VERSION != ''
        with:
          file-path: release/crx-${{ github.event.repository.name }}-${{ steps.semver.outputs.VERSION }}.zip
          extension-id: ${{ vars.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

      - run: yarn release
        if: steps.semver.outputs.VERSION != ''
        env:
          RELEASE_PATH: release/crx-${{ github.event.repository.name }}-${{ steps.semver.outputs.VERSION }}
          VERSION: ${{ steps.semver.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
